apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum
  namespace: quantum
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quantum
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quantum
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: quantum
          image: ghcr.io/gtsteffaniak/filebrowser:0.8.8-beta
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config-values
              mountPath: /config.yaml
              subPath: config.yaml
          envFrom:
            - secretRef:
                name: quantum-env-secret
            - configMapRef:
                name: quantum-env
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: quantum-data
        - name: config-values
          configMap:
            name: quantum-config
