apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - data.pvc.yaml
  - env.configmap.yaml

configMapGenerator:
  - name: quantum-config
    namespace: quantum
    files:
      - config/config.yaml
    options:
      disableNameSuffixHash: true
