apiVersion: v1
kind: Service
metadata:
  name: quantum
  namespace: quantum
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: quantum
  ports:
    - port: 80
      targetPort: 80
      name: http
