server:
  sources:
    - path: /data
      name: data
      config:
        defaultEnabled: true
  externalUrl: "https://quantum.home.legrandleo.fr"
auth:
  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      clientId: "filebrowser"
      clientSecret: "UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh"
      issuerUrl: "http://authelia.authelia.svc.cluster.local"
      scopes: "email openid profile groups"
      userIdentifier: "preferred_username"
      disableVerifyTLS: false
      logoutRedirectUrl: ""
      createUser: true
      adminGroup: "admin"
      groupsClaim: "groups"
