apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blocky
  namespace: blocky
spec:
  rules:
    - host: blocky.home.legrandleo.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blocky
                port:
                  name: http
