apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ingress.yaml
  - deployment.yaml
  - service.yaml
  - loadbalancer.yaml

configMapGenerator:
  - name: blocky-config
    namespace: blocky
    files:
      - config/config.yml
    options:
      disableNameSuffixHash: true
