apiVersion: v1
kind: Service
metadata:
  name: changedetection
  namespace: changedetection
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: changedetection
  ports:
    - port: 80
      targetPort: 5000
      name: http
