apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authelia
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authelia
    spec:
      enableServiceLinks: false
      containers:
        - name: authelia
          image: ghcr.io/authelia/authelia:4.39
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-values
              mountPath: /config/configuration.yml
              subPath: configuration.yml
            - name: config-files
              mountPath: /config/rsa.key
              subPath: rsa.key
          envFrom:
            - secretRef:
               name: authelia-env-secret
            - configMapRef:
               name: authelia-env
      volumes:
        - name: config
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
        - name: config-values
          configMap:
            name: authelia-config
        - name: config-files
          secret:
            secretName: authelia-files-secret
