apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - postgres

configMapGenerator:
  - name: authelia-config
    namespace: authelia
    files:
      - config/configuration.yml
    options:
      disableNameSuffixHash: true
