apiVersion: v1
kind: ConfigMap
metadata:
  name: rwmarkable-env
  namespace: rwmarkable
data:
  NODE_ENV: production
  SSO_MODE: oidc
  APP_URL: http://rwmarkable.rwmarkable.svc.cluster.local
  OIDC_CLIENT_ID: rwmarkable
  OIDC_ISSUER: http://authelia.authelia.svc.cluster.local/.well-known/openid-configuration
  SSO_FALLBACK_LOCAL: "false"
  OIDC_ADMIN_GROUPS: admins
