apiVersion: v1
kind: Service
metadata:
  name: rwmarkable
  namespace: rwmarkable
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rwmarkable
  ports:
    - port: 3000
      targetPort: 3000
