apiVersion: v1
kind: Service
metadata:
  name: cyberchef
  namespace: cyberchef
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cyberchef
  ports:
    - port: 80
      targetPort: 80
      name: http
