apiVersion: v1
kind: ConfigMap
metadata:
  name: lldap-env
  namespace: lldap
data:
  UID: "1000"
  GID: "1000"
  TZ: Europe/Paris
  LLDAP_LDAP_PORT: "389"
  LLDAP_LDAP_BASE_DN: dc=home,dc=legrandleo,dc=fr
