apiVersion: apps/v1
kind: Deployment
metadata:
  name: jotty
  namespace: jotty
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jotty
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jotty
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: jotty
          image: ghcr.io/fccview/jotty:1.10.2
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: config
              mountPath: /app/config
          envFrom:
            # - secretRef:
            #     name: rwmarkable-env-secret
            - configMapRef:
                name: jotty-env
      volumes:
        - name: config
          configMap:
            name: jotty-config
        - name: data
          persistentVolumeClaim:
            claimName: jotty-data
