apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jotty
  namespace: jotty
spec:
  rules:
    - host: jotty.home.legrandleo.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jotty
                port:
                  name: http
