apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - data.pvc.yaml
  - env.configmap.yaml

configMapGenerator:
  - name: jotty-config
    namespace: jotty
    files:
      - config/emojis.json
      - config/themes.json
    options:
      disableNameSuffixHash: true
