apiVersion: v1
kind: Service
metadata:
  name: jotty
  namespace: jotty
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jotty
  ports:
    - port: 80
      targetPort: 3000
      name: http
