apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: location-redirect
  namespace: traefik
spec:
  plugin:
    htransformation:
      Rules:
        - Rule:
          Name: 'Location rewriteValue'
          Header: Location
          Value: '^http://authelia\.authelia\.svc\.cluster\.local(.*)$'
          ValueReplace: 'https://authelia.home.legrandleo.fr$1'
          Type: 'RewriteValueRule'
          SetOnResponse: true
