apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: location-redirect
  namespace: traefik
spec:
  plugin:
    htransformation:
      Rules:
        - Rule:
          Name: 'Location rewriteValue'
          Header: 'Foo'
          Value: 'Bar'
          Type: 'Set'
          SetOnResponse: true
