ingressRoute:
  dashboard:
    enabled: true
    entryPoints: [websecure]
    matchRule: Host(`traefik.home.legrandleo.fr`)
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
  websecure:
    middlewares:
      - authelia@kubernetescrd
tlsStore:
  default:
    defaultCertificate:
      secretName: home-certificate
service:
  externalIPs:
    - 192.168.1.200
providers:
  kubernetesCRD:
    allowCrossNamespace: true
experimental:
  plugins:
    htransformation:
      moduleName: "https://github.com/tomMoulard/htransformation"
      version: "v0.4.1"
