configVersion: 0.0.1
groupName: acme.legrandleo.fr
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager
issuers:
  - name: letsencrypt-issuer
    create: true
    kind: ClusterIssuer
    namespace: cert-manager
    acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
    email: contact@legrandleo.fr
    ovhEndpointName: ovh-eu
    ovhAuthenticationRef:
      applicationKeyRef:
        name: ovh-credentials
        key: applicationKey
      applicationSecretRef:
        name: ovh-credentials
        key: applicationSecret
      consumerKeyRef:
        name: ovh-credentials
        key: consumerKey
