apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: filebrowser
  template:
    metadata:
      labels:
        app.kubernetes.io/name: filebrowser
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser
          volumeMounts:
            - name: config
              mountPath: /config
            - name: database
              mountPath: /database
            - name: data
              mountPath: /srv
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: filebrowser-config
        - name: database
          persistentVolumeClaim:
            claimName: filebrowser-database
        - name: data
          persistentVolumeClaim:
            claimName: filebrowser-data
