apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grist
  namespace: grist
spec:
  rules:
    - host: grist.home.legrandleo.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grist
                port:
                  name: http
