apiVersion: v1
kind: Service
metadata:
  name: grist
  namespace: grist
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grist
  ports:
    - port: 80
      targetPort: 80
      name: http
