apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-env
  namespace: forgejo
data:
  USER_UID: "1000"
  USER_GID: "1000"
  FORGEJO__database__DB_TYPE: postgres
  FORGEJO__database__HOST: postgres:5432
  FORGEJO__database__NAME: forgejo
  FORGEJO__database__USER: forgejo
  FORGEJO__database__PASSWD: forgejo
