apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx-env
  namespace: paperless-ngx
data:
  USERMAP_UID: "1000"
  USERMAP_GID: "1000"
  PAPERLESS_URL: https://paperless.home.legrandleo.fr
  PAPERLESS_OCR_LANGUAGE: fr
  PAPERLESS_TIME_ZONE: Europe/Paris
  PAPERLESS_REDIS: redis://redis:6379
  PAPERLESS_DBENGINE: postgres
  PAPERLESS_DBHOST: postgres
  PAPERLESS_DBNAME: paperless
  PAPERLESS_DBUSER: paperless
  PAPERLESS_DB_READ_CACHE_ENABLED: "true"
