apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - data.pvc.yaml
  #- deployment.yaml
  - env.configmap.yaml
  #- service.yaml
  #- ingress.yaml
  - redis
  - postgres
